version: '3'
services:
  caddy:
    build: ./proxy
    ports:
      - "80:8080"
    links:
      - api:mashup-api
    restart: always
  api:
    build: .
    restart: always
    depends_on:
      - caddy